defaults:
  - agent: CTAC_simple
  - env: stable_non_normal_2D
  - _self_

seed: 42
hydra:
  run:
    dir: .
  output_subdir: null
wandb:
  project_name: CTAC_experiments
  entity: null
  mode: online
  name: CTAC_run_01
  group: debug