environment_params:
  _target_: src.env_rk_jax.JAXDDEEnv
  A:
    _target_: numpy.array
    object: [[0, -1], [1, 0]]
    dtype: float64
  B: 
    _target_: numpy.array
    object: [[0], [1]]
    dtype: float64
  Q: 
    _target_: numpy.array
    object: [[1, 0], [0, 1]]
    dtype: float64
  R: 
    _target_: numpy.array
    object: [[0.1]]
    dtype: float64
  A1:
    _target_: numpy.zeros
    _args_: 
      - [2, 2]
    dtype: float64
  delay: 
    _target_: numpy.zeros
    _args_: 
      - 2
    dtype: float64
  
  step_size: 0.01
  resolution: 5
use_rk4: true